name: CI/CD Workflow
on:
  push:
    branches:
      - main
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - run: pip install -r backend/requirements.txt
#      - run: pytest backend/tests/
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
      - run: npm install
#      - run: npm test
